### ISSUE TITLE
build_neighbor_table fails for Vector{Bond} for open lattices

### ISSUE THREAD

**Issue by lgresista** [SmoQySuite/LatticeUtilities.jl#8]
Hi there,

first of all, thank you for the very nice package! It is super cleanly written and has made writing several lattice based codes in my PHD much easier. 

I stumbled on my issue when trying to use `build_neighbor_table` on a vector of bonds. It occurs for a lattice with open boundary conditions of size 1 in at least one direction. A MWE is the following:

```julia
square = UnitCell(lattice_vecs = [[1.,0.],[0.,1.]],
                     basis_vecs   = [[0.,0.]])

bond_x = Bond((1, 1), (1, 0))
bond_y = Bond((1, 1), (0, 1))

L = [2, 1]

lattice = Lattice(L, [true, false])

neighbor_table = build_neighbor_table([bond_x,bond_y], square, lattice)
```
which returns an error

```julia
MethodError: no method matching Matrix{Int64}(::Vector{Any})
The type `Matrix{Int64}` exists, but no method is defined for this combination of argument types when trying to construct it.
```

The problem is that no y-bonds occur in this lattice and thus
```julia
neighbor_table = build_neighbor_table(bond_y, square, lattice)
``` 
returns `Any[]` instead of a 2 x N `Matrix{Int}`.  This results in `push!(neighbor_tables, neighbor_table)` to fail.

A quick fix, which would also make the function `build_neighbor_table` more type-stable, would be to add an if statement at the end:
```julia
function build_neighbor_table(bond::Bond{D}, unit_cell::UnitCell{D}, lattice::Lattice{D}) where {D}

    (; N) = lattice
    (; displacement, orbitals) = bond

    # initialize empty neighbor table
    neighbor_table = Vector{Int}[]

    # iterate over all unit cells
    for u in 1:N
        # get initial site
        s = loc_to_site(u, orbitals[1], unit_cell)
        # get final site
        s′ = site_to_site(s, displacement, orbitals[2], unit_cell, lattice)
        # check if final site was found
        if s′ != 0
            # add to neighbor table
            push!(neighbor_table, [s,s′])
        end
    end

    # Add if clause here:
    if isempty(neighbor_table)
        return zeros(Int, 2, 0)
    else
        return hcat(neighbor_table...)
    end
end
```

It is kind of a niche use case, but in my ED code I sometimes need `L = [1, 1]` sized spin clusters, and then this comes up. Would it be possible to include this?

**Comment by cohensbw** [comment]
Oh, this a good idea! I'll definitely make this change and publish a release of the package so that this edge case is handled appropriately.

**Comment by lgresista** [comment]
Thanks for the quick reply and implementation!
